# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
highlighter: rouge
markdown: kramdown
disqus: darren987469
google_analytics: darren987469
title: darren987469

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: darren987469

description: Stylish Jekyll Theme
author:
  name: darren987469
  email: darren987469@gmail.com
  github: darren987469
  twitter:
  pinterest:
  linkedin: darren987469
  bio:
  email_md5:

rss_path: feed.xml
categories_path: categories
tags_path: tags
about_path: about

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

permalink: /:title/
plugins:
  - jekyll-paginate
